# Generated by Django 5.1.9 on 2025-06-21 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomina", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="empleado",
            old_name="salario_mensual",
            new_name="salario",
        ),
        migrations.RemoveField(
            model_name="empleado",
            name="fecha_ingreso",
        ),
        migrations.AddField(
            model_name="empleado",
            name="identificacion",
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="PagoNomina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periodo", models.CharField(max_length=50)),
                ("fecha_pago", models.DateTimeField(auto_now_add=True)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nomina.empleado",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Nomina",
        ),
    ]
