# Generated by Django 5.1.9 on 2025-06-21 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empleado", "0001_initial"),
        ("nomina", "0002_rename_salario_mensual_empleado_salario_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagonomina",
            name="empleado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="empleado.empleado"
            ),
        ),
        migrations.AlterField(
            model_name="pagonomina",
            name="descripcion",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="pagonomina",
            name="fecha_pago",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="pagonomina",
            name="periodo",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="pagonomina",
            name="valor",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.DeleteModel(
            name="Empleado",
        ),
    ]
