# Generated by Django 5.1.9 on 2025-06-21 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="asientocontable",
            name="creado_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="cuentacontable",
            name="padre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contabilidad.cuentacontable",
            ),
        ),
        migrations.AlterField(
            model_name="cuentacontable",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("ACTIVO", "Activo"),
                    ("PASIVO", "Pasivo"),
                    ("PATRIMONIO", "Patrimonio"),
                    ("INGRESO", "Ingreso"),
                    ("GASTO", "Gasto"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lineaasiento",
            name="descripcion",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
